"""bio added

Revision ID: 0724d5ffde9e
Revises: c9f2f24e379b
Create Date: 2024-04-09 04:30:04.368064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0724d5ffde9e'
down_revision = 'c9f2f24e379b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(length=250), nullable=True))

    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(length=250), nullable=True))

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(length=250), nullable=True))

    with op.batch_alter_table('scouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(length=250), nullable=True))

    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.drop_column('bio')

    with op.batch_alter_table('scouts', schema=None) as batch_op:
        batch_op.drop_column('bio')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('bio')

    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('bio')

    with op.batch_alter_table('academies', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
