"""empty message

Revision ID: a3fea7c9420f
Revises: b3ad70ae2615
Create Date: 2024-03-29 04:15:46.244222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3fea7c9420f'
down_revision = 'b3ad70ae2615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academies', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=2048),
               existing_nullable=True)

    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=2048),
               existing_nullable=True)

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=2048),
               existing_nullable=True)

    with op.batch_alter_table('scouts', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=2048),
               existing_nullable=True)

    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=2048),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=2048),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=True)

    with op.batch_alter_table('scouts', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=2048),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=True)

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=2048),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=True)

    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=2048),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=True)

    with op.batch_alter_table('academies', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=2048),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###
