"""new migration

Revision ID: af8d218dc223
Revises: a3fea7c9420f
Create Date: 2024-04-02 03:13:38.333666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af8d218dc223'
down_revision = 'a3fea7c9420f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academies', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=2048),
               nullable=False)

    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=2048),
               nullable=False)

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=70), nullable=False))
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=2048),
               nullable=False)

    with op.batch_alter_table('scouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=70), nullable=False))
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=2048),
               nullable=False)

    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=70), nullable=False))
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=2048),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=2048),
               nullable=True)
        batch_op.drop_column('gender')

    with op.batch_alter_table('scouts', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=2048),
               nullable=True)
        batch_op.drop_column('gender')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=2048),
               nullable=True)
        batch_op.drop_column('gender')

    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=2048),
               nullable=True)

    with op.batch_alter_table('academies', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=2048),
               nullable=True)

    # ### end Alembic commands ###
