"""migration

Revision ID: b3ad70ae2615
Revises: 
Create Date: 2024-03-22 23:10:19.517136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3ad70ae2615'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academies',
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=16), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clubs',
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=16), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('surname', sa.String(length=120), nullable=False),
    sa.Column('DOB', sa.Date(), nullable=False),
    sa.Column('position', sa.String(length=120), nullable=True),
    sa.Column('club', sa.String(length=120), nullable=True),
    sa.Column('academy', sa.String(length=120), nullable=True),
    sa.Column('profile_image_path', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=16), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sponsors',
    sa.Column('organization', sa.String(length=120), nullable=True),
    sa.Column('profile_image_path', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=16), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scouts',
    sa.Column('surname', sa.String(length=120), nullable=False),
    sa.Column('DOB', sa.Date(), nullable=False),
    sa.Column('profile_image_path', sa.String(length=255), nullable=True),
    sa.Column('club_id', sa.String(length=120), nullable=True),
    sa.Column('academy_id', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=16), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['academy_id'], ['academies.id'], ),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('video_path', sa.String(length=255), nullable=True),
    sa.Column('video_thumbnail_path', sa.String(length=255), nullable=True),
    sa.Column('player_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    op.drop_table('scouts')
    op.drop_table('sponsors')
    op.drop_table('players')
    op.drop_table('clubs')
    op.drop_table('academies')
    # ### end Alembic commands ###
