"""another migration

Revision ID: c9f2f24e379b
Revises: dfb2f15ea621
Create Date: 2024-04-02 03:34:05.477330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9f2f24e379b'
down_revision = 'dfb2f15ea621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=70),
               type_=sa.String(length=120),
               existing_nullable=True)

    with op.batch_alter_table('scouts', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=70),
               type_=sa.String(length=120),
               existing_nullable=True)

    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=70),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=70),
               existing_nullable=True)

    with op.batch_alter_table('scouts', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=70),
               existing_nullable=True)

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=70),
               existing_nullable=True)

    # ### end Alembic commands ###
