"""another migration

Revision ID: dfb2f15ea621
Revises: af8d218dc223
Create Date: 2024-04-02 03:27:47.832941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dfb2f15ea621'
down_revision = 'af8d218dc223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=70),
               nullable=True)

    with op.batch_alter_table('scouts', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=70),
               nullable=True)

    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=70),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=70),
               nullable=False)

    with op.batch_alter_table('scouts', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=70),
               nullable=False)

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=70),
               nullable=False)

    # ### end Alembic commands ###
