"""dob added to sponsor table

Revision ID: e66bf43e847e
Revises: 4dbd06492a94
Create Date: 2024-04-15 18:30:44.202782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e66bf43e847e'
down_revision = '4dbd06492a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('DOB', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.drop_column('DOB')

    # ### end Alembic commands ###
