"""empty message

Revision ID: 355b094cd68d
Revises: 
Create Date: 2024-03-26 14:29:55.392939

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '355b094cd68d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_path', sa.String(length=255), nullable=True))

    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_path', sa.String(length=255), nullable=True))

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image_path', sa.String(length=255), nullable=True))
        batch_op.alter_column('DOB',
               existing_type=mysql.INTEGER(),
               type_=sa.Date(),
               existing_nullable=False)

    with op.batch_alter_table('scouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image_path', sa.String(length=255), nullable=True))
        batch_op.alter_column('DOB',
               existing_type=mysql.INTEGER(),
               type_=sa.Date(),
               existing_nullable=False)

    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.drop_column('profile_image_path')

    with op.batch_alter_table('scouts', schema=None) as batch_op:
        batch_op.alter_column('DOB',
               existing_type=sa.Date(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('profile_image_path')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('DOB',
               existing_type=sa.Date(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('profile_image_path')

    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('logo_path')

    with op.batch_alter_table('academies', schema=None) as batch_op:
        batch_op.drop_column('logo_path')

    # ### end Alembic commands ###
