"""empty message

Revision ID: 61d82a9aa7b0
Revises: 6fdc5fce2286
Create Date: 2024-03-28 03:56:13.675558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d82a9aa7b0'
down_revision = '6fdc5fce2286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('DOB',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('DOB',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
