"""empty message

Revision ID: afeec1194e23
Revises: 355b094cd68d
Create Date: 2024-03-26 14:42:11.452524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afeec1194e23'
down_revision = '355b094cd68d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('video_path', sa.String(length=255), nullable=True),
    sa.Column('video_thumbnail_path', sa.String(length=255), nullable=True),
    sa.Column('player_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    # ### end Alembic commands ###
