"""empty message

Revision ID: cbfb2fa0c4a2
Revises: edada5727698
Create Date: 2024-04-02 14:45:32.561467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbfb2fa0c4a2'
down_revision = 'edada5727698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academies', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=2048),
               nullable=False)

    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=2048),
               nullable=False)

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=120), nullable=True))
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=2048),
               nullable=False)

    with op.batch_alter_table('scouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=120), nullable=True))
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=2048),
               nullable=False)

    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=120), nullable=True))
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=2048),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=2048),
               nullable=True)
        batch_op.drop_column('gender')

    with op.batch_alter_table('scouts', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=2048),
               nullable=True)
        batch_op.drop_column('gender')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=2048),
               nullable=True)
        batch_op.drop_column('gender')

    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=2048),
               nullable=True)

    with op.batch_alter_table('academies', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=2048),
               nullable=True)

    # ### end Alembic commands ###
