"""empty message

Revision ID: edada5727698
Revises: 61d82a9aa7b0
Create Date: 2024-03-28 04:49:55.161305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edada5727698'
down_revision = '61d82a9aa7b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('DOB',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('DOB',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
